# https://github.com/ElasticHQ/elasticsearch-HQ/blob/master/example/docker-compose-local-dev.yml
version: '2.2'
services:
  mongo:
    image: mongo:4.2.6
    container_name: mongodb
    volumes:
      - /data/liked/mongo
    ports:
      - 27017:27017

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: elasticsearch
    environment:
#      - cluster.name=elasticsearch
#      - node.name=node_1
#      - network.host=0.0.0.0
#      - network.publish_host=0.0.0.0
#      - bootstrap.memory_lock=true
#      - http.cors.enabled=false
#      - http.cors.allow-origin=*
#      - http.host=0.0.0.0
#      - transport.host=0.0.0.0
#      - bootstrap.system_call_filter=false
#      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - /data/liked/elastic
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  elastic-hq:
    image: elastichq/elasticsearch-hq
    container_name: elasticsearch-hq
    environment:
      - HQ_DEFAULT_URL=http://elasticsearch:9200
      - HQ_DEBUG=True
      - HQ_ENABLE_SSL=True
      - HQ_VERIFY_CERTS=False
    ports:
      - 5000:5000
    networks:
      - elastic

networks:
  elastic:
    driver: bridge