mongo:
  image: mongo:4.2.6
  container_name: mongodb
  volumes:
    - /data/liked/mongo
  ports:
    - 27017:27017

elastic:
  image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
  container_name: elasticsearch
  environment:
    - "discovery.type=single-node"
  volumes:
    - /data/liked/elastic
  ports:
    - 9200:9200
